/**
 * POST /api/crm/quote
 *
 * Edgar (the RevOps home-chat quote builder) builds the quote entirely
 * within RevOps — this endpoint is what pushes it into Zoho. On purpose,
 * it never touches Zoho Books: quotes live as real Zoho CRM Quote records,
 * linked to the customer's Account via a proper lookup (not a text string),
 * with dealer cost / margin on custom fields for internal visibility. The
 * PDF is generated by RevOps itself and attached directly to the Quote
 * record, so it's visible right on the CRM file without ever going near
 * Books. Books only enters the picture later, when a deal actually closes.
 *
 * Body: {
 *   customerName, accountCity?, accountState?, contactPerson?, email?,
 *   lineItems: [{name, description?, quantity, rate, cost}],
 *   shippingCost?, notes?, validDays?  (default 30)
 * }
 * Returns: { ok, quoteId, accountId, accountCreated, attachmentOk, total, reviewUrl }
 */
import { getZohoToken } from '../_lib/zoho-token.js'
import { setCors }      from '../_lib/cors.js'
import { generateQuotePdf } from '../_lib/quotePdf.js'
import { findOrCreateZohoAccount } from '../_lib/zohoAccount.js'
import { CRM_BASE, zohoCrmHeaders, zohoCrmCreateRecord } from '../_lib/zohoCrm.js'

export const config = { api: { bodyParser: { sizeLimit: '2mb' } } }

export default async function handler(req, res) {
  setCors(res, 'POST, OPTIONS')
  if (req.method === 'OPTIONS') return res.status(200).end()
  if (req.method !== 'GET' && req.method !== 'POST') return res.status(405).json({ error: 'GET or POST only' })

  // ── LIST recent quotes — for the Edgar Quotes nav screen ────────────────────
  if (req.method === 'GET') {
    let token
    try { token = await getZohoToken() } catch (err) { return res.status(500).json({ error: err.message, setup: '/api/zoho-setup' }) }
    const headers = zohoCrmHeaders(token)
    try {
      const fields = ['Subject', 'Account_Name', 'Quote_Stage', 'Valid_Till', 'Created_Time', 'Grand_Total', 'Total_Dealer_Cost', 'Gross_Profit', 'GP_Percent'].join(',')
      const r = await fetch(`${CRM_BASE}/Quotes?fields=${fields}&sort_by=Created_Time&sort_order=desc&per_page=50`, { headers })
      const data = await r.json().catch(() => null)
      if (!r.ok && r.status !== 204) return res.status(r.status).json({ error: data?.message || 'Failed to list quotes' })
      return res.json({ quotes: data?.data || [] })
    } catch (err) {
      return res.status(500).json({ error: err.message })
    }
  }

  const {
    customerName, accountCity, accountState, contactPerson, email,
    lineItems = [], shippingCost = 0, notes = '', validDays = 30,
  } = req.body || {}

  if (!customerName)    return res.status(400).json({ error: 'customerName required' })
  if (!lineItems.length) return res.status(400).json({ error: 'lineItems required' })

  let token
  try { token = await getZohoToken() } catch (err) { return res.status(500).json({ error: err.message, setup: '/api/zoho-setup' }) }
  const headers = zohoCrmHeaders(token)

  try {
    // 1. Resolve/create the Account first — this is what makes the Quote
    //    actually show up under the Account in Zoho, instead of floating free.
    const { id: accountId, created: accountCreated } = await findOrCreateZohoAccount(
      { name: customerName, city: accountCity, state: accountState }, headers
    )
    if (!accountId) return res.status(502).json({ error: 'Could not find or create the Zoho Account for ' + customerName })

    // 2. Totals. Margin fields are internal-only — never rendered on the
    //    customer-facing PDF, only stored on the CRM record.
    const subtotal    = lineItems.reduce((s, li) => s + (Number(li.quantity) || 0) * (Number(li.rate) || 0), 0)
    const totalCost   = lineItems.reduce((s, li) => s + (Number(li.quantity) || 0) * (Number(li.cost)  || 0), 0) + Number(shippingCost || 0)
    const grossProfit = subtotal - totalCost
    const gpPercent    = subtotal > 0 ? (grossProfit / subtotal) * 100 : 0

    const today     = new Date()
    const dateStr   = today.toISOString().slice(0, 10)
    const validTill = new Date(today.getTime() + Number(validDays || 30) * 86_400_000).toISOString().slice(0, 10)

    // 3. Create the Quote. Quoted_Items subform uses Zoho's stock field
    //    names — best-effort: if the shape doesn't match this org's setup,
    //    retry once without it rather than losing the whole quote over it.
    const quotePayload = {
      Subject:           `${customerName} — ${dateStr}`,
      Account_Name:      { id: accountId },
      Valid_Till:        validTill,
      Description:       notes || '',
      Total_Dealer_Cost: Number(totalCost.toFixed(2)),
      Total_Shipping:    Number(Number(shippingCost || 0).toFixed(2)),
      Gross_Profit:      Number(grossProfit.toFixed(2)),
      GP_Percent:        Number(gpPercent.toFixed(2)),
      Quoted_Items: lineItems.map(li => ({
        Product_Name: li.name || 'Item',
        Quantity:     Number(li.quantity) || 1,
        List_Price:   Number(li.rate) || 0,
      })),
    }

    let rec = await zohoCrmCreateRecord('Quotes', quotePayload, headers)

    if (rec?.status === 'error') {
      const { Quoted_Items, ...withoutSubform } = quotePayload
      rec = await zohoCrmCreateRecord('Quotes', withoutSubform, headers)
    }

    if (rec?.status === 'error') {
      return res.status(502).json({ error: rec.message || 'Zoho quote creation failed', raw: rec })
    }
    const quoteId = rec?.details?.id
    if (!quoteId) return res.status(502).json({ error: 'Zoho did not return a quote id' })

    // Pull the real Quote_Number for the PDF — the create response only
    // ever returns the record id, autonumber fields aren't echoed back.
    let quoteNumber = quoteId
    try {
      const numRes = await fetch(`${CRM_BASE}/Quotes/${quoteId}?fields=Quote_Number`, { headers })
      const numData = await numRes.json().catch(() => null)
      quoteNumber = numData?.data?.[0]?.Quote_Number || quoteId
    } catch { /* fall back to id */ }

    // 4. Generate the PDF in RevOps (sell prices only), attach it directly
    //    to the Quote record, and hand the same bytes back to the caller —
    //    the rep can download it or email it straight from the approve UI
    //    without a second trip through Zoho.
    let attachmentOk = false
    let pdfBase64 = null
    try {
      const pdfBytes = await generateQuotePdf({
        quoteNumber, date: dateStr, validUntil: validTill,
        customerName, contactPerson, lineItems, notes,
      })
      pdfBase64 = Buffer.from(pdfBytes).toString('base64')

      const form = new FormData()
      form.append('file', new Blob([pdfBytes], { type: 'application/pdf' }), `Quote-${quoteNumber}.pdf`)
      const attachRes = await fetch(`${CRM_BASE}/Quotes/${quoteId}/Attachments`, {
        method:  'POST',
        headers: { Authorization: `Zoho-oauthtoken ${token}` },
        body:    form,
      })
      const attachData = await attachRes.json().catch(() => null)
      attachmentOk = attachRes.ok && attachData?.data?.[0]?.status !== 'error'
      if (!attachmentOk) console.warn('[crm/quote] attachment rejected:', JSON.stringify(attachData))
    } catch (err) {
      console.error('[crm/quote] PDF generation/attach failed:', err.message)
    }

    return res.json({
      ok: true,
      quoteId,
      quoteNumber,
      accountId,
      accountCreated,
      attachmentOk,
      pdfBase64,
      total: subtotal,
      reviewUrl: `https://crm.zoho.com/crm/tab/Quotes/${quoteId}`,
    })

  } catch (err) {
    console.error('[crm/quote]', err.message)
    return res.status(500).json({ error: err.message })
  }
}
