-- Command Center supporting tables
-- Run once via: supabase db push  OR  psql $DATABASE_URL -f this_file.sql

-- Custom tools registered via ToolManager (mirrors localStorage st1_custom_tools)
CREATE TABLE IF NOT EXISTS custom_tools (
  id           TEXT PRIMARY KEY,
  name         TEXT NOT NULL,
  capabilities TEXT[]  NOT NULL DEFAULT '{}',
  type         TEXT    NOT NULL DEFAULT 'webhook',
  config       JSONB   NOT NULL DEFAULT '{}',
  enabled      BOOLEAN NOT NULL DEFAULT TRUE,
  roles        TEXT[]  NOT NULL DEFAULT '{admin}',
  created_by   TEXT,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Email / outreach templates generated by SalesCopyModule
CREATE TABLE IF NOT EXISTS email_templates (
  id           BIGSERIAL PRIMARY KEY,
  name         TEXT    NOT NULL,
  email_type   TEXT    NOT NULL,
  subject      TEXT,
  body         TEXT    NOT NULL,
  org          TEXT,
  sport        TEXT,
  created_by   TEXT,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Research notes saved from ResearchModule
CREATE TABLE IF NOT EXISTS intel_notes (
  id           BIGSERIAL PRIMARY KEY,
  query        TEXT    NOT NULL,
  output       TEXT    NOT NULL,
  tags         TEXT[]  NOT NULL DEFAULT '{}',
  created_by   TEXT,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Keep updated_at current on custom_tools
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS custom_tools_updated_at ON custom_tools;
CREATE TRIGGER custom_tools_updated_at
  BEFORE UPDATE ON custom_tools
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
